Repository rodrigofnobrega/desafio-eject-back-end, pull requests merged in 2024-10, with the labels that each got.

#2 refactor: Organizar models
  .gitignore
  apps/admin.py
  apps/footer/__init__.py
  apps/footer/admin.py
  apps/footer/apps.py
  apps/footer/migrations/0001_initial.py
  apps/footer/migrations/__init__.py
  apps/footer/models.py
  apps/footer/tests.py
  apps/footer/urls.py
  apps/footer/views.py
  apps/forum/__init__.py
  apps/forum/admin.py
  apps/forum/apps.py
  apps/forum/migrations/0001_initial.py
  apps/forum/migrations/__init__.py
  apps/forum/models.py
  apps/forum/tests.py
  apps/forum/urls.py
  apps/forum/views.py
  apps/home/__init__.py
  apps/home/admin.py
  apps/home/apps.py
  apps/home/migrations/0001_initial.py
  apps/home/migrations/0002_rename_tools_tool.py
  apps/home/migrations/__init__.py
  apps/home/models.py
  apps/home/tests.py
  apps/home/urls.py
  apps/home/views.py
  apps/migrations/0001_initial.py
  apps/migrations/0002_comment_contact_drawingandcardandknow_information_and_more.py
  apps/models.py
  apps/pais_profs/__init__.py
  apps/pais_profs/admin.py
  apps/pais_profs/apps.py
  apps/pais_profs/migrations/0001_initial.py
  apps/pais_profs/migrations/__init__.py
  apps/pais_profs/models.py
  apps/pais_profs/tests.py
  apps/pais_profs/urls.py
  apps/pais_profs/views.py
  apps/urls.py
  apps/videos/__init__.py
  apps/videos/admin.py
  apps/videos/apps.py
  apps/videos/migrations/0001_initial.py
  apps/videos/migrations/0002_rename_videos_video.py
  apps/videos/migrations/__init__.py
  apps/videos/models.py
  apps/videos/tests.py
  apps/videos/urls.py
  apps/videos/views.py
  apps/views.py
  manicursos/settings.py
  manicursos/urls.py
Labels: refactor

#8 feat: Dinamizar fórum
  apps/forum/models.py
  apps/forum/urls.py
  apps/forum/utils.py
  apps/forum/views.py
  apps/pais_profs/admin.py
  apps/pais_profs/models.py
  apps/pais_profs/views.py
  core/templates/forum.html
  core/templates/parents.html
Labels: enhancement

#11 Rodrigo/feat/mudancas pontuais
  README.md
  apps/footer/admin.py
  apps/footer/migrations/0002_remove_information_randomurl1_and_more.py
  apps/footer/models.py
  apps/footer/utils.py
  apps/forum/admin.py
  apps/forum/migrations/0003_pagedescription.py
  apps/forum/migrations/0004_topimage_delete_topimagef.py
  apps/forum/migrations/0005_topimage_pos.py
  apps/forum/models.py
  apps/forum/utils.py
  apps/forum/views.py
  apps/home/admin.py
  apps/home/migrations/0006_platformdesc.py
  apps/home/migrations/0007_forumitens.py
  apps/home/migrations/0008_supportmaterial.py
  apps/home/models.py
  apps/home/views.py
  apps/pais_profs/views.py
  apps/videos/admin.py
  apps/videos/migrations/0007_pagedescription.py
  apps/videos/models.py
  apps/videos/views.py
  core/templates/footer.html
  core/templates/forum.html
  core/templates/home.html
  core/templates/videos.html
Labels: documentation, enhancement, refactor

#12 Feat: novos models para 'videos'
  apps/videos/admin.py
  apps/videos/migrations/0008_topimagevideo1_topimagevideo2_topimagevideo3_and_more.py
  apps/videos/models.py
  apps/videos/views.py
  core/templates/videos.html
Labels: enhancement

#13 Docs: atualizar README e corrigir navbar
  README.md
  core/static/css/global.css
  core/templates/forum.html
  core/templates/home.html
  core/templates/navbar.html
  core/templates/parents.html
  core/templates/templates.html
  core/templates/videos.html
Labels: bug, documentation
